common: &common
  adapter: postgresql
  username: Skerou

development:
  <<: *common
  database: oxynum_dev

test:
  <<: *common
  database: oxynum_test

production:
  <<: *common
  database: oxynum_prod